### ISSUE TITLE
derelict-ogg : Failed to load symbol oggpack_writecheck from shared library libogg.dll

### ISSUE THREAD

**Issue by tanitta** [ludumdare36-team-rc/maingame#48]
https://github.com/DerelictOrg/DerelictOgg/issues/1

**Comment by tanitta** [comment]
https://github.com/DerelictOrg/DerelictOgg/blob/master/source/derelict/ogg/ogg.d
の
L115
L189
L268
を消すと実行できるかも．

**Comment by ray45422** [comment]
エラーの出る箇所をひたすらコメントアウトしていきましたが、ogg.dllでエラーが出なくなると次はvorbis.dllを要求され、そちらでもエラーが出るのでひたすらコメントアウトすると次はlibvorbisenc.dllを要求されキリがなさそう。

**Comment by tanitta** [comment]
libvorbisencもいらないのでもうちょいガンガンやってみるのはどうだろう

**Comment by tanitta** [comment]
derelict改変無しで同様のエラーがでました．
`Failed to load symbol oggpack_writecheck from shared library libogg.dll`

ビルド環境
- windows7 64bit 
- DMD32 D Compiler v2.071.1
- DUB version 0.9.24, built on Sep 20 2015
- derelict-ogg 1.0.1
- derelict-vorbis 1.0.1

**Comment by tanitta** [comment]
https://github.com/dhewm/dhewm3-libs
