### ISSUE TITLE
tutorialの実装

### ISSUE THREAD

**Issue by tanitta** [ludumdare36-team-rc/maingame#49]

**Comment by OtObOx** [comment]
チュートリアルの画像作成は間に合わないので
背景黒で偉人の言葉表示（案）

The humanrace is governed by its imagination.
 Napoleon, 1769～1821

意味は「人間は、その想像力によって支配される。」

**Comment by OtObOx** [comment]
Let's make the highest tower in the space.
No warehouse is game over.
Enemies try to break warehouse.
To save food,make the house and weapon.
Then,Pop can go to space!
